routes/web.php
<?php

use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// book detail
Route::get('/book/{id}', [App\Http\Controllers\BookController::class, 'show'])->name('book.show');

Route::middleware(['auth'])->group(function() {

    // Transactions
    Route::post('/transactions/request-borrow', [App\Http\Controllers\TransactionController::class, 'requestBorrow'])->name('transactions.request-borrow');


    Route::get('/cart', [App\Http\Controllers\CartController::class, 'index'])->name('cart.index');
    Route::get('/cart/add/{bookId}', [App\Http\Controllers\CartController::class, 'addToCart'])->name('cart.add');
    Route::get('/cart/remove/{bookId}', [App\Http\Controllers\CartController::class, 'removeFromCart'])->name('cart.remove');
    Route::post('/cart/update-quantity', [App\Http\Controllers\CartController::class, 'changeQuantity'])->name('cart.update-quantity');

    Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function() {
        Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

        // Shelf Routes
        Route::get('shelves/json', [App\Http\Controllers\ShelfController::class, 'getShelvesJson'])->name('shelves.json');
        Route::resource('shelves', App\Http\Controllers\ShelfController::class)->except('show');

        // Book Routes
        Route::get('books/json', [App\Http\Controllers\BookController::class, 'getBooksJson'])->name('books.json');
        Route::resource('books', App\Http\Controllers\BookController::class)->except('show');

        // User Routes
        Route::post('users/change-status/{id}/{status}', [App\Http\Controllers\UserController::class, 'changeStatus'])->name('users.change-status');
        Route::get('users/request/json', [App\Http\Controllers\UserController::class, 'getRequestJson'])->name('users.request.json');
        Route::get('users/admin/json', [App\Http\Controllers\UserController::class, 'getAdminJson'])->name('users.admin.json');
        Route::get('users/member/json', [App\Http\Controllers\UserController::class, 'getMemberJson'])->name('users.member.json');
        Route::resource('users', App\Http\Controllers\UserController::class);

        // Transaction Routes
        Route::post('transactions/change-status/{id}/{status}', [App\Http\Controllers\TransactionController::class, 'changeStatus'])->name('transactions.change-status');
        Route::get('transactions/json', [App\Http\Controllers\TransactionController::class, 'getTransactionJson'])->name('transactions.json');
        Route::get('transactions', [App\Http\Controllers\TransactionController::class, 'index'])->name('transactions.index');
    });
});

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0">Dashboard</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="">Library</a></li>
                    <li class="breadcrumb-item active">Dashboard</li>
                </ol>
            </div>

        </div>
    </div>

    <div class="row">
        <div class="col-xl-4">
            <div class="card bg-primary">
                <div class="card-body">
                    <div class="text-center py-3">
                        <ul class="bg-bubbles ps-0">
                            <li><i class="bx bx-grid-alt font-size-24"></i></li>
                            <li><i class="bx bx-tachometer font-size-24"></i></li>
                            <li><i class="bx bx-store font-size-24"></i></li>
                            <li><i class="bx bx-cube font-size-24"></i></li>
                            <li><i class="bx bx-cylinder font-size-24"></i></li>
                            <li><i class="bx bx-command font-size-24"></i></li>
                            <li><i class="bx bx-hourglass font-size-24"></i></li>
                            <li><i class="bx bx-pie-chart-alt font-size-24"></i></li>
                            <li><i class="bx bx-coffee font-size-24"></i></li>
                            <li><i class="bx bx-polygon font-size-24"></i></li>
                        </ul>
                        <div class="main-wid position-relative">
                            <h3 class="text-white">Library Dashboard</h3>

                            <h3 class="text-white mb-0"> Welcome Back, {{ Auth::user()->name }}!</h3>

                            <div class="mt-4 pt-2 mb-2">
                                <a href="{{ route('home') }}" class="btn btn-success">Back to home <i class="mdi mdi-arrow-right ms-1"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-8">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="avatar">
                                <span class="avatar-title bg-soft-primary rounded">
                                    <i class="mdi mdi-shopping-outline text-primary font-size-24"></i>
                                </span>
                            </div>
                            <p class="text-muted mt-4 mb-0">Today Orders</p>
                            <h4 class="mt-1 mb-0">3,89,658 <sup class="text-success fw-medium font-size-14"><i class="mdi mdi-arrow-down"></i> 10%</sup></h4>
                            <div>
                                <div class="py-3 my-1">
                                    <div id="mini-1" data-colors='["#3980c0"]'></div>
                                </div>
                                <ul class="list-inline d-flex justify-content-between justify-content-center mb-0">
                                    <li class="list-inline-item"><a href="#" class="text-muted">Day</a></li>
                                    <li class="list-inline-item"><a href="#" class="text-muted">Week</a></li>
                                    <li class="list-inline-item"><a href="#" class="text-muted">Month</a></li>
                                    <li class="list-inline-item"><a href="#" class="text-muted">Year</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="avatar">
                                <span class="avatar-title bg-soft-success rounded">
                                    <i class="mdi mdi-eye-outline text-success font-size-24"></i>
                                </span>
                            </div>
                            <p class="text-muted mt-4 mb-0">Today Visitor</p>
                            <h4 class="mt-1 mb-0">1,648,29 <sup class="text-danger fw-medium font-size-14"><i class="mdi mdi-arrow-down"></i> 19%</sup></h4>
                            <div>
                                <div class="py-3 my-1">
                                    <div id="mini-2" data-colors='["#33a186"]'></div>
                                </div>
                                <ul class="list-inline d-flex justify-content-between justify-content-center mb-0">
                                    <li class="list-inline-item"><a href="#" class="text-muted">Day</a></li>
                                    <li class="list-inline-item"><a href="#" class="text-muted">Week</a></li>
                                    <li class="list-inline-item"><a href="#" class="text-muted">Month</a></li>
                                    <li class="list-inline-item"><a href="#" class="text-muted">Year</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="avatar">
                                <span class="avatar-title bg-soft-primary rounded">
                                    <i class="mdi mdi-rocket-outline text-primary font-size-24"></i>
                                </span>
                            </div>
                            <p class="text-muted mt-4 mb-0">Total Expense</p>
                            <h4 class="mt-1 mb-0">6,48,249 <sup class="text-success fw-medium font-size-14"><i class="mdi mdi-arrow-down"></i> 22%</sup></h4>
                            <div>
                                <div class="py-3 my-1">
                                    <div id="mini-3" data-colors='["#3980c0"]'></div>
                                </div>
                                <ul class="list-inline d-flex justify-content-between justify-content-center mb-0">
                                    <li class="list-inline-item"><a href="#" class="text-muted">Day</a></li>
                                    <li class="list-inline-item"><a href="#" class="text-muted">Week</a></li>
                                    <li class="list-inline-item"><a href="#" class="text-muted">Month</a></li>
                                    <li class="list-inline-item"><a href="#" class="text-muted">Year</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="avatar">
                                <span class="avatar-title bg-soft-success rounded">
                                    <i class="mdi mdi-account-multiple-outline text-success font-size-24"></i>
                                </span>
                            </div>
                            <p class="text-muted mt-4 mb-0">New Users</p>
                            <h4 class="mt-1 mb-0">$5,265,3 <sup class="text-danger fw-medium font-size-14"><i class="mdi mdi-arrow-down"></i> 18%</sup></h4>
                            <div>
                                <div class="py-3 my-1">
                                    <div id="mini-4" data-colors='["#33a186"]'></div>
                                </div>
                                <ul class="list-inline d-flex justify-content-between justify-content-center mb-0">
                                    <li class="list-inline-item"><a href="#" class="text-muted">Day</a></li>
                                    <li class="list-inline-item"><a href="#" class="text-muted">Week</a></li>
                                    <li class="list-inline-item"><a href="#" class="text-muted">Month</a></li>
                                    <li class="list-inline-item"><a href="#" class="text-muted">Year</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="col-lg-3 col-md-6 main-menu" onclick="location.href='{{ route('users.index') }}'" >
            <div class="card">
                <div class="card-body p-3 d-flex">
                    <div class="avatar mr-5">
                        <span class="avatar-title bg-soft-primary rounded">
                            <i class="mdi mdi-account text-primary font-size-24"></i>
                        </span>
                    </div>
                    <div class="flex-fill">
                        <p class="fw-bold font-size-20" style="margin-top: 0; margin-left: 20px; margin-bottom: 0">User</p>
                        <p class="font-size-14" style="margin-top: 0; margin-left: 20px; margin-bottom: 0">Manage User Data</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6 main-menu" onclick="location.href='{{ route('shelves.index') }}'" >
            <div class="card">
                <div class="card-body p-3 d-flex">
                    <div class="avatar mr-5">
                        <span class="avatar-title bg-soft-primary rounded">
                            <i class="mdi mdi-bookshelf text-primary font-size-24"></i>
                        </span>
                    </div>
                    <div class="flex-fill">
                        <p class="fw-bold font-size-20" style="margin-top: 0; margin-left: 20px; margin-bottom: 0">Shelf</p>
                        <p class="font-size-14" style="margin-top: 0; margin-left: 20px; margin-bottom: 0">Manage Location Book</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6 main-menu" onclick="location.href='{{ route('books.index') }}'" >
            <div class="card">
                <div class="card-body p-3 d-flex">
                    <div class="avatar mr-5">
                        <span class="avatar-title bg-soft-primary rounded">
                            <i class="mdi mdi-book-open text-primary font-size-24"></i>
                        </span>
                    </div>
                    <div class="flex-fill">
                        <p class="fw-bold font-size-20" style="margin-top: 0; margin-left: 20px; margin-bottom: 0">Book</p>
                        <p class="font-size-14" style="margin-top: 0; margin-left: 20px; margin-bottom: 0">Manage Book</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6 main-menu" onclick="location.href='{{ route('transactions.index') }}'" >
            <div class="card">
                <div class="card-body p-3 d-flex">
                    <div class="avatar mr-5">
                        <span class="avatar-title bg-soft-primary rounded">
                            <i class="mdi mdi-swap-horizontal text-primary font-size-24"></i>
                        </span>
                    </div>
                    <div class="flex-fill">
                        <p class="fw-bold font-size-20" style="margin-top: 0; margin-left: 20px; margin-bottom: 0">Transaction</p>
                        <p class="font-size-14" style="margin-top: 0; margin-left: 20px; margin-bottom: 0">Borrow and return</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0">Home</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="">Library</a></li>
                    <li class="breadcrumb-item active">Home</li>
                </ol>
            </div>

        </div>
    </div>

    <div class="row">
        <div class="col-xl-3 col-lg-4">
            <div class="card">
                <div class="card-header bg-transparent border-bottom">
                    <h5 class="mb-0">Filters</h5>
                </div>

                <div class="p-4 border-top">
                    <div>
                        <h5 class="font-size-14 mb-0"><a href="#filterproduct-category-collapse" class="collapsed text-dark d-block" data-bs-toggle="collapse">Categories <i class="mdi mdi-chevron-up float-end accor-down-icon"></i></a></h5>

                        <div class="collapse" id="filterproduct-category-collapse">
                            <div class="mt-4">
                                @foreach ($categories as $category)
                                    <div class="custom-control custom-radio mt-2">
                                        <input type="radio" id="{{ $category->name }}" name="category" class="custom-control-input">
                                        <label class="custom-control-label" for="{{ $category->name }}">{{ $category->name }}</label>
                                    </div>
                                @endforeach
                            </div>
                        </div>

                    </div>
                </div>

                <div class="custom-accordion">
                    <div class="p-4 border-top">
                        <div>
                            <h5 class="font-size-14 mb-0"><a href="#filtershelf-collapse" class="text-dark d-block" data-bs-toggle="collapse">Shelf <i class="mdi mdi-chevron-up float-end accor-down-icon"></i></a></h5>

                            <div class="collapse show" id="filtershelf-collapse">
                                <div class="mt-4">
                                    @foreach ($shelves as $shelf)
                                        <div class="custom-control custom-radio mt-2">
                                            <input type="radio" id="{{ $shelf->code }}" name="shelf" class="custom-control-input">
                                            <label class="custom-control-label" for="{{ $shelf->code }}">{{ $shelf->code }}</label>
                                        </div>
                                    @endforeach
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="p-4 border-top">
                        <div>
                            <h5 class="font-size-14 mb-0"><a href="#filterproduct-color-collapse" class="text-dark d-block" data-bs-toggle="collapse">Customer Rating <i class="mdi mdi-chevron-up float-end accor-down-icon"></i></a></h5>

                            <div class="collapse show" id="filterproduct-color-collapse">
                                <div class="mt-4">
                                    <div class="form-check mt-2">
                                        <input type="radio" id="productratingRadio1" name="productratingRadio1" class="form-check-input">
                                        <label class="form-check-label" for="productratingRadio1">4 <i class="mdi mdi-star text-warning"></i> & Above</label>
                                    </div>
                                    <div class="form-check mt-2">
                                        <input type="radio" id="productratingRadio2" name="productratingRadio1" class="form-check-input">
                                        <label class="form-check-label" for="productratingRadio2">3 <i class="mdi mdi-star text-warning"></i> & Above</label>
                                    </div>
                                    <div class="form-check mt-2">
                                        <input type="radio" id="productratingRadio3" name="productratingRadio1" class="form-check-input">
                                        <label class="form-check-label" for="productratingRadio3">2 <i class="mdi mdi-star text-warning"></i> & Above</label>
                                    </div>
                                    <div class="form-check mt-2">
                                        <input type="radio" id="productratingRadio4" name="productratingRadio1" class="form-check-input">
                                        <label class="form-check-label" for="productratingRadio4">1 <i class="mdi mdi-star text-warning"></i></label>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>

            </div>
        </div>

        <div class="col-xl-9 col-lg-8">
            <div class="card">
                <div class="card-body">
                    <div>
                        <div class="row">
                            <div class="col-md-6">
                                <div>
                                    @if (Request::get('search'))
                                        <h5>Showing result for "{{ Request::get('search') }}"</h5>
                                    @endif
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-inline float-md-end">
                                    <div class="search-box ms-2">
                                        <div class="position-relative">
                                            <input type="text" class="form-control bg-light border-light rounded" placeholder="Search...">
                                            <i class="mdi mdi-magnify search-icon"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>


                        <div class="row">
                            @foreach ($books as $book)
                                <div class="col-xl-4 col-sm-6" onclick="location.href='{{ route('book.show', $book->id) }}'">
                                    <div class="product-box">
                                        <div class="product-img pt-4 px-4">
                                            <div class="product-wishlist">
                                                <a href="{{ route('cart.add', $book->id) }}">
                                                    <i class="mdi mdi-cart-outline"></i>
                                                </a>
                                            </div>
                                            <img src="{{ env('APP_URL') . '/storage//' . ($book->cover ? $book->cover : 'no-cover.jpg') }}" alt="" class="img-fluid mx-auto d-block">
                                        </div>

                                        <div class="product-content p-4">

                                            <div class="d-flex justify-content-between align-items-end">
                                                <div>
                                                    <h5 class="mb-1"><a href="#" class="text-dark font-size-16">{{ $book->title }}</a></h5>
                                                    <p class="text-muted font-size-13">{{ $book->category . ' | ' . $book->shelf }}</p>
                                                    <h5 class="mt-3 mb-0"><span class="text-muted me-2">By {{ $book->author }}</h5>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                                @endforeach
                        </div>
                        <!-- end row -->
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection