routes/web.php
<?php

use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// book detail
Route::get('/book/{id}', [App\Http\Controllers\BookController::class, 'show'])->name('book.show');

Route::middleware(['auth'])->group(function() {

    // Transactions
    Route::post('/transactions/request-borrow', [App\Http\Controllers\TransactionController::class, 'requestBorrow'])->name('transactions.request-borrow');


    Route::get('/cart', [App\Http\Controllers\CartController::class, 'index'])->name('cart.index');
    Route::get('/cart/add/{bookId}', [App\Http\Controllers\CartController::class, 'addToCart'])->name('cart.add');
    Route::get('/cart/remove/{bookId}', [App\Http\Controllers\CartController::class, 'removeFromCart'])->name('cart.remove');
    Route::post('/cart/update-quantity', [App\Http\Controllers\CartController::class, 'changeQuantity'])->name('cart.update-quantity');

    Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function() {
        Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

        // Shelf Routes
        Route::get('shelves/json', [App\Http\Controllers\ShelfController::class, 'getShelvesJson'])->name('shelves.json');
        Route::resource('shelves', App\Http\Controllers\ShelfController::class)->except('show');

        // Book Routes
        Route::get('books/json', [App\Http\Controllers\BookController::class, 'getBooksJson'])->name('books.json');
        Route::resource('books', App\Http\Controllers\BookController::class)->except('show');

        // User Routes
        Route::post('users/change-status/{id}/{status}', [App\Http\Controllers\UserController::class, 'changeStatus'])->name('users.change-status');
        Route::get('users/request/json', [App\Http\Controllers\UserController::class, 'getRequestJson'])->name('users.request.json');
        Route::get('users/admin/json', [App\Http\Controllers\UserController::class, 'getAdminJson'])->name('users.admin.json');
        Route::get('users/member/json', [App\Http\Controllers\UserController::class, 'getMemberJson'])->name('users.member.json');
        Route::resource('users', App\Http\Controllers\UserController::class);

        // Transaction Routes
        Route::post('transactions/change-status/{id}/{status}', [App\Http\Controllers\TransactionController::class, 'changeStatus'])->name('transactions.change-status');
        Route::get('transactions/json', [App\Http\Controllers\TransactionController::class, 'getTransactionJson'])->name('transactions.json');
        Route::get('transactions', [App\Http\Controllers\TransactionController::class, 'index'])->name('transactions.index');
    });
});

resources/views/shelves/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0">Shelves</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('shelves.index') }}">Shelves</a></li>
                    <li class="breadcrumb-item active">Create</li>
                </ol>
            </div>

        </div>
    </div>

    <div class="card">
        <div class="p-4 border-top">
            <form method="POST" action="{{ route('shelves.store') }}">
                @csrf

                <div class="row">
                    <div class="col-sm-6">
                        <div class="mb-3">
                            <label class="form-label" for="code">Code<span class="fw-bold text-danger">*</strong></label>
                            <input id="code" name="code" type="text" class="form-control @error('code') is-invalid @enderror" readonly value="{{ $code }}">
                            @error('code')
                                <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="mb-3">
                            <label class="form-label" for="location">Location<span class="fw-bold text-danger">*</strong></label>
                            <input id="location" name="location" placeholder="Enter Location" type="text" class="form-control @error('location') is-invalid @enderror" value="{{ old('location') }}">
                            @error('location')
                                <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="mb-0">
                    <label class="form-label" for="metadescription">Description</label>
                    <textarea class="form-control" id="metadescription" placeholder="Enter Description" rows="4">{{ old('address') }}</textarea>
                    @error('description')
                        <span class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="row mt-3">
                    <div class="col text-end">
                        <a href="{{ route('shelves.index') }}" class="btn btn-danger"> <i class="bx bx-x me-1"></i> Cancel </a>
                        <button type="submit" class="btn btn-success"> <i class=" bx bx-file me-1"></i> Save </a>
                    </div> <!-- end col -->
                </div> <!-- end row-->
            </form>
        </div>
    </div>
@endsection

@push('scripts')
@endpush

resources/views/shelves/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0">Shelves</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('shelves.index') }}">Shelves</a></li>
                    <li class="breadcrumb-item active">Edit</li>
                </ol>
            </div>

        </div>
    </div>

    <div class="card">
        <div class="p-4 border-top">
            <form method="POST" action="{{ route('shelves.update', $shelf->id) }}">
                @method('PATCH')
                @csrf

                <div class="row">
                    <div class="col-sm-6">
                        <div class="mb-3">
                            <label class="form-label" for="code">Code<span class="fw-bold text-danger">*</strong></label>
                            <input id="code" name="code" type="text" class="form-control @error('code') is-invalid @enderror" readonly value="{{ $shelf->code }}">
                            @error('code')
                                <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="mb-3">
                            <label class="form-label" for="location">Location<span class="fw-bold text-danger">*</strong></label>
                            <input id="location" name="location" placeholder="Enter Location" type="text" class="form-control @error('location') is-invalid @enderror" value="{{ old('location') ?? $shelf->location }}">
                            @error('location')
                                <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="mb-0">
                    <label class="form-label" for="metadescription">Description</label>
                    <textarea class="form-control" id="metadescription" placeholder="Enter Description" rows="4">{{ old('address') ?? $shelf->description }}</textarea>
                    @error('description')
                        <span class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="row mt-3">
                    <div class="col text-end">
                        <a href="{{ route('shelves.index') }}" class="btn btn-danger"> <i class="bx bx-x me-1"></i> Cancel </a>
                        <button type="submit" class="btn btn-success"> <i class=" bx bx-file me-1"></i> Save </a>
                    </div> <!-- end col -->
                </div> <!-- end row-->
            </form>
        </div>
    </div>
@endsection

@push('scripts')
@endpush

resources/views/shelves/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0">Shelves</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Shelves</li>
                </ol>
            </div>

        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">All Shelves</h4>
                    <div class="card-header-action">
                        <a href="{{ route('shelves.create') }}" class="btn btn-primary btn-sm">
                            <i class="mdi mdi-plus"></i> Create
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table mb-0" id="shelvesTable">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Code</th>
                                    <th>Location</th>
                                    <th>Description</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>

                </div>
            </div>
            <!-- end card -->
        </div>
        <!-- end col -->
    </div>
@endsection

@push('scripts')
    <script type="text/javascript">
        $(document).ready(function() {
            // DataTable
            $('#shelvesTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('shelves.json') }}",
                columns: [{
                        name: 'no',
                        data: 'id',
                        render: function(data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        },
                        orderable: false,
                    },
                    {
                        name: 'code',
                        data: 'code',
                        orderable: true
                    },
                    {
                        name: 'location',
                        data: 'location',
                        orderable: false
                    },
                    {
                        name: 'description',
                        data: 'description',
                        orderable: false,
                    },
                    {
                        name: 'action',
                        data: 'action',
                        orderable: false
                    },
                ]
            });

        });
    </script>
@endpush