routes/web.php
<?php

use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// book detail
Route::get('/book/{id}', [App\Http\Controllers\BookController::class, 'show'])->name('book.show');

Route::middleware(['auth'])->group(function() {

    // Transactions
    Route::post('/transactions/request-borrow', [App\Http\Controllers\TransactionController::class, 'requestBorrow'])->name('transactions.request-borrow');


    Route::get('/cart', [App\Http\Controllers\CartController::class, 'index'])->name('cart.index');
    Route::get('/cart/add/{bookId}', [App\Http\Controllers\CartController::class, 'addToCart'])->name('cart.add');
    Route::get('/cart/remove/{bookId}', [App\Http\Controllers\CartController::class, 'removeFromCart'])->name('cart.remove');
    Route::post('/cart/update-quantity', [App\Http\Controllers\CartController::class, 'changeQuantity'])->name('cart.update-quantity');

    Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function() {
        Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

        // Shelf Routes
        Route::get('shelves/json', [App\Http\Controllers\ShelfController::class, 'getShelvesJson'])->name('shelves.json');
        Route::resource('shelves', App\Http\Controllers\ShelfController::class)->except('show');

        // Book Routes
        Route::get('books/json', [App\Http\Controllers\BookController::class, 'getBooksJson'])->name('books.json');
        Route::resource('books', App\Http\Controllers\BookController::class)->except('show');

        // User Routes
        Route::post('users/change-status/{id}/{status}', [App\Http\Controllers\UserController::class, 'changeStatus'])->name('users.change-status');
        Route::get('users/request/json', [App\Http\Controllers\UserController::class, 'getRequestJson'])->name('users.request.json');
        Route::get('users/admin/json', [App\Http\Controllers\UserController::class, 'getAdminJson'])->name('users.admin.json');
        Route::get('users/member/json', [App\Http\Controllers\UserController::class, 'getMemberJson'])->name('users.member.json');
        Route::resource('users', App\Http\Controllers\UserController::class);

        // Transaction Routes
        Route::post('transactions/change-status/{id}/{status}', [App\Http\Controllers\TransactionController::class, 'changeStatus'])->name('transactions.change-status');
        Route::get('transactions/json', [App\Http\Controllers\TransactionController::class, 'getTransactionJson'])->name('transactions.json');
        Route::get('transactions', [App\Http\Controllers\TransactionController::class, 'index'])->name('transactions.index');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'gender',
        'phone_number',
        'address',
        'avatar'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    public function index()
    {
        $data['pageTitle'] = 'Users';

        return view('users.index', $data);
    }

    public function create()
    {
        return view('users.create');
    }

    public function store(UserStoreRequest $request)
    {
        $imageName = null;

        if ($request->hasFile('avatar')) {
            $imageName = time() . '.' . $request->avatar->extension();
            $request->avatar->storeAs('public', $imageName);
        }

        DB::table('users')->insert([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'gender' => $request->gender,
            'status' => true,
            'phone_number' => $request->phone_number,
            'address' => $request->address,
            'role' => $request->role,
            'avatar' => $imageName,
            'created_at' => now(),
            'updated_at' => now()
        ]);

        return redirect()->route('users.index')->with('success', 'User created successfully.');
    }

    public function show($id)
    {
        $data['pageTitle'] = 'User Details';
        $data['user'] = DB::table('users')->where('id', $id)->first();

        return view('users.show', $data);
    }

    public function edit($id)
    {
        $data['pageTitle'] = 'Edit User';
        $data['user'] = DB::table('users')->where('id', $id)->first();

        return view('users.edit', $data);
    }

    public function update(UserUpdateRequest $request, $id)
    {
        $user = DB::table('users')->where('id', $id)->first();
        $imageName = $user->avatar;


        if ($request->avatar_default || $request->hasFile('avatar')) {
            $imageName = null;
            if (Storage::exists('public/' . $user->avatar)) {
                Storage::delete('public/' . $user->avatar);
            }
        }

        if ($request->hasFile('avatar')) {
            $imageName = time() . '.' . $request->avatar->extension();
            $request->avatar->storeAs('public', $imageName);
        }

        DB::table('users')->where('id', $id)->update([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'gender' => $request->gender,
            'phone_number' => $request->phone_number,
            'address' => $request->address,
            'role' => $request->role,
            'avatar' => $imageName,
            'updated_at' => now()
        ]);

        return redirect()->route('users.index')->with('success', 'User updated successfully.');;
    }

    public function destroy($id)
    {
        $user = DB::table('users')->where('id', $id)->first();
        if (Storage::exists('public/' . $user->avatar)) {
            Storage::delete('public/' . $user->avatar);
        }

        DB::table('users')->where('id', $id)->delete();

        return response()->json(['message' => 'User deleted successfully.']);
    }

    public function changeStatus($id, $status)
    {
        DB::table('users')->where('id', $id)->update([
            'status' => $status == 'false' ? 0 : 1,
            'updated_at' => now()
        ]);

        return response()->json(['message' => 'User status changed successfully.']);
    }

    /* Method for datatable that returning json */
    public function getRequestJson(Request $request)
    {
        $draw = $request->get('draw');
        $start = $request->get("start"); // Start counting from this
        $rowPerPage = $request->get("length"); // total number of rows per page

        $columnIndexArr = $request->get('order');
        $columnNameArr = $request->get('columns');
        $orderArr = $request->get('order');
        $searchArr = $request->get('search');

        $columnIndex = $columnIndexArr[0]['column']; // Column index
        $columnName = $columnNameArr[$columnIndex]['data']; // Column name
        $columnSortOrder = $orderArr[0]['dir']; // asc or desc
        $searchValue = $searchArr['value']; // Search value

        // Total records
        $totalRecords = DB::table('users')->where('status', false)->where('role', 'member')->select('count(*) as allcount')->count();
        $totalRecordswithFilter = DB::table('users')->where('status', false)->where('role', 'member')->select('count(*) as allcount')->where('name', 'like', '%' . $searchValue . '%')->count();

        // Get records, also we have included search filter as well
        $records = DB::table('users')->orderBy($columnName, $columnSortOrder)
            ->where('role', 'member')
            ->where('status', false)
            ->where(function ($q) use ($searchValue) {
                $q->where('users.name', 'like', '%' . $searchValue . '%')
                    ->orWhere('users.email', 'like', '%' . $searchValue . '%');
            })
            ->select([
                'users.*',
            ])
            ->skip($start)
            ->take($rowPerPage)
            ->get();

        $data = [];

        foreach ($records as $record) {
            $avatarUrl = env('APP_URL') . '/storage//' . ($record->avatar ? $record->avatar : 'no-cover.jpg');

            array_push($data, [
                "id" => $record->id,
                "name" => '<img src="' . $avatarUrl . '" alt="" class="avatar-sm rounded-circle me-2">
                            <a href="#" class="text-body">' . $record->name . '</a>',
                "email" => $record->email,
                "status" => '<input type="checkbox" id="' . $record->id . '" switch="success" ' . ($record->status ? 'checked' : '') . '  onChange="changeStatus(this.checked, ' . $record->id . ')"/>
                            <label for="' . $record->id . '" data-on-label="Yes" data-off-label="No"></label>',
                "action" => '<ul class="list-inline mb-0">
                                <li class="list-inline-item">
                                    <a href="' . route('users.edit', $record->id) . '" class="px-2 text-primary"><i class="bx bx-pencil font-size-18"></i></a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#" class="px-2 text-danger" onClick="modalDelete(\'Member\', \'' . $record->name . '\', \'' . route('users.destroy', $record->id) . '\', \'' . route('users.index') . '\')"><i class="bx bx-trash-alt font-size-18"></i></a>
                                </li>
                            </ul>',
            ]);
        }

        $response = array(
            "draw" => intval($draw),
            "iTotalRecords" => $totalRecords,
            "iTotalDisplayRecords" => $totalRecordswithFilter,
            "aaData" => $data,
        );

        echo json_encode($response);
    }

    public function getMemberJson(Request $request)
    {
        $draw = $request->get('draw');
        $start = $request->get("start"); // Start counting from this
        $rowPerPage = $request->get("length"); // total number of rows per page

        $columnIndexArr = $request->get('order');
        $columnNameArr = $request->get('columns');
        $orderArr = $request->get('order');
        $searchArr = $request->get('search');

        $columnIndex = $columnIndexArr[0]['column']; // Column index
        $columnName = $columnNameArr[$columnIndex]['data']; // Column name
        $columnSortOrder = $orderArr[0]['dir']; // asc or desc
        $searchValue = $searchArr['value']; // Search value

        // Total records
        $totalRecords = DB::table('users')->where('status', true)->where('role', 'member')->select('count(*) as allcount')->count();
        $totalRecordswithFilter = DB::table('users')->where('status', true)->where('role', 'member')->select('count(*) as allcount')->where('name', 'like', '%' . $searchValue . '%')->count();

        // Get records, also we have included search filter as well
        $records = DB::table('users')->orderBy($columnName, $columnSortOrder)
            ->where('role', 'member')
            ->where('status', true)
            ->where(function ($q) use ($searchValue) {
                $q->where('users.name', 'like', '%' . $searchValue . '%')
                    ->orWhere('users.email', 'like', '%' . $searchValue . '%');
            })
            ->select([
                'users.*',
            ])
            ->skip($start)
            ->take($rowPerPage)
            ->get();

        $data = [];

        foreach ($records as $record) {
            $avatarUrl = env('APP_URL') . '/storage//' . ($record->avatar ? $record->avatar : 'no-cover.jpg');

            array_push($data, [
                "id" => $record->id,
                "name" => '<img src="' . $avatarUrl . '" alt="" class="avatar-sm rounded-circle me-2">
                            <a href="#" class="text-body">' . $record->name . '</a>',
                "email" => $record->email,
                "status" => '<input type="checkbox" id="' . $record->id . '" switch="success" ' . ($record->status ? 'checked' : '') . '  onChange="changeStatus(this.checked, ' . $record->id . ')"/>
                            <label for="' . $record->id . '" data-on-label="Yes" data-off-label="No"></label>',
                "action" => '<ul class="list-inline mb-0">
                                <li class="list-inline-item">
                                    <a href="' . route('users.edit', $record->id) . '" class="px-2 text-primary"><i class="bx bx-pencil font-size-18"></i></a>
                                </li>
                                <li class="list-inline-item">

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0">Users</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('users.index') }}">Users</a></li>
                    <li class="breadcrumb-item active">Create</li>
                </ol>
            </div>

        </div>
    </div>

    <div class="card">
        <div class="p-4 border-top">
            <form method="POST" action="{{ route('users.store') }}" enctype="multipart/form-data">
                @csrf

                <div class="mb-3">
                    <label class="form-label" for="name">Name</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" placeholder="Enter Name" name="name" value="{{ old('name') }}">
                    @error('name')
                        <span class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <label class="form-label" for="email">Email</label>
                    <input type="email" class="form-control @error('email') is-invalid @enderror" id="email" placeholder="Enter email" name="email" value="{{ old('email') }}">
                    @error('email')
                        <span class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <label class="form-label" for="phone_number">Phone Number</label>
                    <input class="form-control @error('phone_number') is-invalid @enderror" type="tel" placeholder="Enter Phone Number" id="phone_number" name="phone_number" value="{{ old('phone_number') }}">
                    @error('phone_number')
                        <span class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <label class="form-label" for="avatar">Avatar</label>
                    <input type="file" class="form-control @error('avatar') is-invalid @enderror" id="avatar" name="avatar" value="{{ old('avatar') }}">
                    @error('avatar')
                        <span class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <label class="form-label" for="address">Address</label>
                    <textarea class="form-control @error('address') is-invalid @enderror" id="address" name="address" rows="3" name="address" placeholder="Enter Address">{{ old('address') }}</textarea>
                    @error('address')
                        <span class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <label class="form-label" for="gender">Gender</label>
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="radio" name="gender" id="male" value="male" checked {{ old('gender') == 'male' ? 'checked' : '' }}>
                        <label class="form-check-label" for="male">
                            Male
                        </label>
                    </div>
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="radio" name="gender" id="female" value="female" {{ old('gender') == 'female' ? 'checked' : '' }}>
                        <label class="form-check-label" for="female">
                            Female
                        </label>
                    </div>
                </div>

                <div class="mb-3">
                    <label class="form-label" for="role">Role</label>
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="radio" name="role" id="admin" value="admin" checked {{ old('role') == 'admin' ? 'checked' : '' }}>
                        <label class="form-check-label" for="admin">
                            Admin
                        </label>
                    </div>
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="radio" name="role" id="member" value="member" {{ old('role') == 'member' ? 'checked' : '' }}>
                        <label class="form-check-label" for="member">
                            Member
                        </label>
                    </div>
                </div>

                <div class="mb-3">
                    <label class="form-label" for="password">Password</label>
                    <input type="password" class="form-control @error('password') is-invalid @enderror" id="password" placeholder="Enter password" name="password">
                    @error('password')
                        <span class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="row mt-3">
                    <div class="col text-end">
                        <a href="{{ route('users.index') }}" class="btn btn-danger"> <i class="bx bx-x me-1"></i> Cancel </a>
                        <button type="submit" class="btn btn-success"> <i class=" bx bx-file me-1"></i> Save </a>
                    </div> <!-- end col -->
                </div> <!-- end row-->
            </form>
        </div>
    </div>
@endsection

@push('scripts')
@endpush

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0">Users</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('users.index') }}">Users</a></li>
                    <li class="breadcrumb-item active">Edit</li>
                </ol>
            </div>

        </div>
    </div>

    <div class="card">
        <div class="p-4 border-top">
            <form method="POST" action="{{ route('users.update', $user->id) }}" enctype="multipart/form-data">
                @method('PATCH')
                @csrf

                <div class="mb-3">
                    <label class="form-label" for="name">Name</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" placeholder="Enter Name" name="name" value="{{ old('name') ?? $user->name }}">
                    @error('name')
                        <span class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <label class="form-label" for="email">Email</label>
                    <input type="email" class="form-control @error('email') is-invalid @enderror" id="email" placeholder="Enter email" name="email" value="{{ old('email') ?? $user->email }}">
                    @error('email')
                        <span class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <label class="form-label" for="phone_number">Phone Number</label>
                    <input class="form-control @error('phone_number') is-invalid @enderror" type="tel" placeholder="Enter Phone Number" id="phone_number" name="phone_number" value="{{ old('phone_number') ?? $user->phone_number }}">
                    @error('phone_number')
                        <span class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <label class="form-label" for="avatar">Avatar</label>
                    <img src="{{ env('APP_URL') . '/storage//' . ($user->avatar ? $user->avatar : 'no-cover.jpg') }}" alt="{{ $user->name }}" class="img-thumbnail" style="width: 200px;">
                    @if ($user->avatar)
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="checkbox" id="avatar_default" name="avatar_default" class="custom-control-input" value="true" {{ old('avatar_default') == true ? 'checked' : '' }}>
                            <label class="custom-control-label" for="avatar_default">Remove</label>
                        </div>
                    @endif
                    <input type="file" class="form-control @error('avatar') is-invalid @enderror" id="avatar" name="avatar" value="{{ old('avatar') }}">
                    @error('avatar')
                        <span class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <label class="form-label" for="address">Address</label>
                    <textarea class="form-control @error('address') is-invalid @enderror" id="address" name="address" rows="3" name="address" placeholder="Enter Address">{{ old('address') ?? $user->address }}</textarea>
                    @error('address')
                        <span class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <label class="form-label" for="gender">Gender</label>
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="radio" name="gender" id="male" value="male" checked {{ (old('gender') ?? $user->gender) == 'male' ? 'checked' : '' }}>
                        <label class="form-check-label" for="male">
                            Male
                        </label>
                    </div>
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="radio" name="gender" id="female" value="female" {{ (old('gender') ?? $user->gender) == 'female' ? 'checked' : '' }}>
                        <label class="form-check-label" for="female">
                            Female
                        </label>
                    </div>
                </div>

                <div class="mb-3">
                    <label class="form-label" for="role">Role</label>
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="radio" name="role" id="admin" value="admin" checked {{ (old('role') ?? $user->role) == 'admin' ? 'checked' : '' }}>
                        <label class="form-check-label" for="admin">
                            Admin
                        </label>
                    </div>
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="radio" name="role" id="member" value="member" {{ (old('role') ?? $user->role) == 'member' ? 'checked' : '' }}>
                        <label class="form-check-label" for="member">
                            Member
                        </label>
                    </div>
                </div>

                <div class="mb-3">
                    <label class="form-label" for="new_password">New Password</label>
                    <input type="password" class="form-control @error('new_password') is-invalid @enderror" id="new_password" placeholder="Enter new password" name="new_password">
                    @error('new_password')
                        <span class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="row mt-3">
                    <div class="col text-end">
                        <a href="{{ route('users.index') }}" class="btn btn-danger"> <i class="bx bx-x me-1"></i> Cancel </a>
                        <button type="submit" class="btn btn-success"> <i class=" bx bx-file me-1"></i> Save </a>
                    </div> <!-- end col -->
                </div> <!-- end row-->
            </form>
        </div>
    </div>
@endsection

@push('scripts')
@endpush