routes/web.php
<?php

use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// book detail
Route::get('/book/{id}', [App\Http\Controllers\BookController::class, 'show'])->name('book.show');

Route::middleware(['auth'])->group(function() {

    // Transactions
    Route::post('/transactions/request-borrow', [App\Http\Controllers\TransactionController::class, 'requestBorrow'])->name('transactions.request-borrow');


    Route::get('/cart', [App\Http\Controllers\CartController::class, 'index'])->name('cart.index');
    Route::get('/cart/add/{bookId}', [App\Http\Controllers\CartController::class, 'addToCart'])->name('cart.add');
    Route::get('/cart/remove/{bookId}', [App\Http\Controllers\CartController::class, 'removeFromCart'])->name('cart.remove');
    Route::post('/cart/update-quantity', [App\Http\Controllers\CartController::class, 'changeQuantity'])->name('cart.update-quantity');

    Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function() {
        Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

        // Shelf Routes
        Route::get('shelves/json', [App\Http\Controllers\ShelfController::class, 'getShelvesJson'])->name('shelves.json');
        Route::resource('shelves', App\Http\Controllers\ShelfController::class)->except('show');

        // Book Routes
        Route::get('books/json', [App\Http\Controllers\BookController::class, 'getBooksJson'])->name('books.json');
        Route::resource('books', App\Http\Controllers\BookController::class)->except('show');

        // User Routes
        Route::post('users/change-status/{id}/{status}', [App\Http\Controllers\UserController::class, 'changeStatus'])->name('users.change-status');
        Route::get('users/request/json', [App\Http\Controllers\UserController::class, 'getRequestJson'])->name('users.request.json');
        Route::get('users/admin/json', [App\Http\Controllers\UserController::class, 'getAdminJson'])->name('users.admin.json');
        Route::get('users/member/json', [App\Http\Controllers\UserController::class, 'getMemberJson'])->name('users.member.json');
        Route::resource('users', App\Http\Controllers\UserController::class);

        // Transaction Routes
        Route::post('transactions/change-status/{id}/{status}', [App\Http\Controllers\TransactionController::class, 'changeStatus'])->name('transactions.change-status');
        Route::get('transactions/json', [App\Http\Controllers\TransactionController::class, 'getTransactionJson'])->name('transactions.json');
        Route::get('transactions', [App\Http\Controllers\TransactionController::class, 'index'])->name('transactions.index');
    });
});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'isbn',
        'category_id',
        'shelf_id',
        'title',
        'published_year',
        'stock',
        'author',
        'publisher',
        'page_count',
        'synopsis',
        'cover'
    ];
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\BookStoreRequest;
use App\Http\Requests\StockRequest;
use App\Models\Book;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class BookController extends Controller
{
    public function index()
    {
        $data['pageTitle'] = 'Books';

        return view('books.index', $data);
    }

    public function create()
    {
        $data['pageTitle'] = 'Add Book';
        $data['categories'] = DB::table('categories')->get();
        $data['shelves'] = DB::table('shelves')->get();

        return view('books.create', $data);
    }

    public function store(BookStoreRequest $request)
    {
        $imageName = null;

        if ($request->hasFile('cover')) {
            $imageName = time() . '.' . $request->cover->extension();
            $request->cover->storeAs('public', $imageName);
        }

        DB::table('books')->insert([
            'isbn' => $request->isbn,
            'category_id' => $request->category,
            'shelf_id' => $request->shelf,
            'title' => $request->title,
            'published_year' => $request->published_year,
            'stock' => $request->stock,
            'author' => $request->author,
            'publisher' => $request->publisher,
            'page_count' => $request->page_count,
            'synopsis' => $request->synopsis,
            'cover' => $imageName,
            'created_at' => now(),
            'updated_at' => now()
        ]);

        return redirect()->route('books.index')->with('success', 'Book created successfully.');
    }

    public function show($id)
    {
        $data['pageTitle'] = 'Book Details';
        $data['book'] = DB::table('books')
        ->where('books.id', $id)
        ->leftJoin('shelves', 'shelves.id', '=', 'books.shelf_id')
        ->leftJoin('categories', 'categories.id', '=', 'books.category_id')
        ->first([
                'books.*',
                'shelves.code as shelf',
                'categories.name as category'
            ]);

        return view('books.show', $data);
    }

    public function edit($id)
    {
        $data['pageTitle'] = 'Edit Book';
        $data['categories'] = DB::table('categories')->get();
        $data['shelves'] = DB::table('shelves')->get();
        $data['book'] = DB::table('books')->where('id', $id)->first();

        return view('books.edit', $data);
    }

    public function update(BookStoreRequest $request, $id)
    {
        $book = DB::table('books')->where('id', $id)->first();
        $imageName = $book->cover;

        if ($request->cover_default || $request->hasFile('cover')) {
            if (Storage::exists('public/' . $book->cover)) {
                Storage::delete('public/' . $book->cover);
                $imageName = null;
            }
        }

        if ($request->hasFile('cover')) {
            $imageName = time() . '.' . $request->cover->extension();
            $request->cover->storeAs('public', $imageName);
        }

        DB::table('books')->where('id', $id)->update([
            'isbn' => $request->isbn,
            'category_id' => $request->category,
            'shelf_id' => $request->shelf,
            'title' => $request->title,
            'published_year' => $request->published_year,
            'author' => $request->author,
            'publisher' => $request->publisher,
            'page_count' => $request->page_count,
            'synopsis' => $request->synopsis,
            'cover' => $imageName,
            'updated_at' => now()
        ]);

        return redirect()->route('books.index')->with('success', 'Book updated successfully.');
    }

    public function destroy($id)
    {
        $book = DB::table('books')->where('id', $id)->first();
        if (Storage::exists('public/' . $book->cover)) {
            Storage::delete('public/' . $book->cover);
        }

        DB::table('books')->where('id', $id)->delete();

        return response()->json(['message' => 'Book deleted successfully.']);
    }

    public function addStock(StockRequest $request, $id)
    {
        DB::table('books')->where('id', $id)->increment('stock', $request->stock);
        DB::table('history_stock_book')->insert([
            'book_id' => $id,
            'stock' => $request->stock,
            'description' => $request->description,
            'created_at' => now(),
            'updated_at' => now()
        ]);

        return response()->json(['message' => 'Add stock book success.']);
    }

    /* Method for datatable that returning json */
    public function getBooksJson(Request $request)
    {
        $draw = $request->get('draw');
        $start = $request->get("start"); // Start counting from this
        $rowPerPage = $request->get("length"); // total number of rows per page

        $columnIndexArr = $request->get('order');
        $columnNameArr = $request->get('columns');
        $orderArr = $request->get('order');
        $searchArr = $request->get('search');

        $columnIndex = $columnIndexArr[0]['column']; // Column index
        $columnName = $columnNameArr[$columnIndex]['data']; // Column name
        $columnSortOrder = $orderArr[0]['dir']; // asc or desc
        $searchValue = $searchArr['value']; // Search value

        // Total records
        $totalRecords = DB::table('books')->select('count(*) as allcount')->count();
        $totalRecordswithFilter = DB::table('books')->select('count(*) as allcount')->where('title', 'like', '%' . $searchValue . '%')->count();

        // Get records, also we have included search filter as well
        $records = DB::table('books')->orderBy($columnName, $columnSortOrder)
            ->where('books.title', 'like', '%' . $searchValue . '%')
            ->orWhere('books.published_year', 'like', '%' . $searchValue . '%')
            ->orWhere('books.author', 'like', '%' . $searchValue . '%')
            ->orWhere('books.publisher', 'like', '%' . $searchValue . '%')
            ->leftJoin('categories', 'books.category_id', '=', 'categories.id')
            ->leftJoin('shelves', 'books.shelf_id', '=', 'shelves.id')
            ->select([
                'books.*',
                'categories.name as category_name',
                'shelves.code as shelf_code',
            ])
            ->skip($start)
            ->take($rowPerPage)
            ->get();

        $data = [];

        $actionButton = '<button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                            Action <i class="mdi mdi-chevron-down"></i>
                        </button>';

        foreach ($records as $record) {
            $coverUrl = env('APP_URL') . '/storage//' . ($record->cover ? $record->cover : 'no-cover.jpg');

            array_push($data, [
                "id" => $record->id,
                "isbn" => $record->isbn,
                "cover" => '<img src="' . $coverUrl . '" alt="" class="avatar-lg">',
                "title" => $record->title,
                "stock" => $record->stock . '<button type="button" class="btn btn-sm btn-success waves-effect waves-light" onClick="addStock(' . $record->id  . ', \'' . $record->title . '\')">+</button>',
                "category" => $record->category_name ?? '-',
                "shelf" => $record->shelf_code ?? '-',
                "action" => $actionButton . ' <ul class="dropdown-menu">
                                                    <li><a class="dropdown-item" href="' . route('books.edit', $record->id) . '">Edit</a></li>
                                                    <li><a
                                                        class="dropdown-item"
                                                        href="#"
                                                        onClick="modalDelete(\'Book\', \'' . $record->title . '\', \'' . route('books.destroy', $record->id) . '\', \'' . route('books.index') . '\')">
                                                            Delete
                                                    </a></li>
                                                </ul>',
            ]);
        }

        $response = array(
            "draw" => intval($draw),
            "iTotalRecords" => $totalRecords,
            "iTotalDisplayRecords" => $totalRecordswithFilter,
            "aaData" => $data,
        );

        echo json_encode($response);
    }
}

resources/views/books/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0">Books</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('books.index') }}">Books</a></li>
                    <li class="breadcrumb-item active">Create</li>
                </ol>
            </div>

        </div>
    </div>

    <div class="card">
        <div class="p-4 border-top">
            <form method="POST" action="{{ route('books.store') }}" enctype="multipart/form-data">
                @csrf

                <div class="row">
                    <div class="col-sm-3">
                        <div class="mb-3">
                            <label class="form-label" for="isbn">ISBN<span class="fw-bold text-danger">*</strong></label>
                            <input id="isbn" name="isbn" type="text" placeholder="Enter ISBN" class="form-control @error('isbn') is-invalid @enderror" value="{{ old('isbn') }}">
                            @error('isbn')
                                <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="mb-3">
                            <label class="form-label" for="title">Title<span class="fw-bold text-danger">*</strong></label>
                            <input id="title" name="title" placeholder="Enter title" type="text" class="form-control @error('title') is-invalid @enderror" value="{{ old('title') }}">
                            @error('title')
                                <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <label for="category" class="form-label font-size-13 text-muted">Category<span class="fw-bold text-danger">*</strong></label>
                        <select class="form-control select2 @error('category') is-invalid @enderror" name="category" id="category">
                            <option value="">Choose Category</option>
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}" {{ old('category') == $category->id ? 'selected' : '' }}>{{ $category->name }}</option>
                            @endforeach
                        </select>
                        @error('category')
                            <span class="invalid-feedback">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="col-sm-3">
                        <div class="mb-3">
                            <label for="shelf" class="form-label font-size-13 text-muted">Shelf<span class="fw-bold text-danger">*</strong></label>
                            <select class="form-control select2 @error('shelf') is-invalid @enderror" name="shelf" id="shelf">
                                <option value="">Choose Shelf</option>
                                @foreach ($shelves as $shelf)
                                    <option value="{{ $shelf->id }}" {{ old('shelf') == $shelf->id ? 'selected' : '' }}>{{ $shelf->code }}</option>
                                @endforeach
                            </select>
                            @error('shelf')
                                <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-2">
                        <div class="mb-3">
                            <label class="form-label" for="published_year">Published Year<span class="fw-bold text-danger">*</strong></label>
                            <input id="published_year" name="published_year" type="number" placeholder="Published Year" class="form-control @error('published_year') is-invalid @enderror" value="{{ old('published_year') }}">
                            @error('published_year')
                                <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="col-sm-2">
                        <div class="mb-3">
                            <label class="form-label" for="stock">Stock<span class="fw-bold text-danger">*</strong></label>
                            <input id="stock" name="stock" placeholder="Enter Stock" type="number" class="form-control @error('stock') is-invalid @enderror" value="{{ old('stock') }}">
                            @error('stock')
                                <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="mb-3">
                            <label class="form-label" for="author">Author<span class="fw-bold text-danger">*</strong></label>
                            <input id="author" name="author" placeholder="Enter Author" type="text" class="form-control @error('author') is-invalid @enderror" value="{{ old('author') }}">
                            @error('author')
                                <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="mb-3">
                            <label class="form-label" for="publisher">Publisher<span class="fw-bold text-danger">*</strong></label>
                            <input id="publisher" name="publisher" placeholder="Enter Publisher" type="text" class="form-control @error('publisher') is-invalid @enderror" value="{{ old('publisher') }}">
                            @error('publisher')
                                <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="col-sm-2">
                        <div class="mb-3">
                            <label class="form-label" for="page_count">Page Count<span class="fw-bold text-danger">*</strong></label>
                            <input id="page_count" name="page_count" placeholder="Enter Page Count" type="number" class="form-control @error('page_count') is-invalid @enderror" value="{{ old('page_count') }}">
                            @error('page_count')
                                <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="mb-3">
                    <label class="form-label" for="cover">Cover</label>
                    <input type="file" class="form-control @error('cover') is-invalid @enderror" id="cover" name="cover" value="{{ old('cover') }}">
                    @error('cover')
                        <span class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="mb-0">
                    <label class="form-label" for="synopsis">Synopsis<span class="fw-bold text-danger">*</strong></label>
                    <textarea class="form-control @error('synopsis') is-invalid @enderror" id="synopsis" placeholder="Enter Synopsis" rows="4" name="synopsis">{{ old('synopsis') }}</textarea>
                    @error('synopsis')
                        <span class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="row mt-3">
                    <div class="col text-end">
                        <a href="{{ route('books.index') }}" class="btn btn-danger"> <i class="bx bx-x me-1"></i> Cancel </a>
                        <button type="submit" class="btn btn-success"> <i class=" bx bx-file me-1"></i> Save </a>
                    </div> <!-- end col -->
                </div> <!-- end row-->
            </form>
        </div>
    </div>
@endsection

@push('scripts')
@endpush

resources/views/books/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0">Books</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Books</li>
                </ol>
            </div>

        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">All Books</h4>
                    <div class="card-header-action">
                        <a href="{{ route('books.create') }}" class="btn btn-primary btn-sm">
                            <i class="mdi mdi-plus"></i> Create
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table mb-0" id="bookTable">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Cover</th>
                                    <th>ISBN</th>
                                    <th>Title</th>
                                    <th>Category</th>
                                    <th>Shelf</th>
                                    <th>Stock</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
            <!-- end card -->
        </div>
        <!-- end col -->
    </div>
@endsection

@push('scripts')
    <script type="text/javascript">
        function addStock(bookId, bookName) {
            Swal.fire({
                title: "Add book stock " + bookName,
                html: '<label for="stock-add">Stock</label>' +
                    '<input id="stock-add" type="number" value="0" class="swal2-input">' +
                    '<textarea id="description" class="swal2-textarea" placeholder="description"></textarea>',
                showCancelButton: !0,
                confirmButtonText: "Submit",
                showLoaderOnConfirm: !0,
                confirmButtonColor: "#3980c0",
                cancelButtonColor: "#f34e4e",
            }).then(function(result) {
                if (result.isConfirmed) {
                    const stock = $('#stock-add').val()
                    const description = $('#description').val()
                    axios({
                        method: 'post',
                        url: "/api/books/add-stock/" + bookId,
                        headers: {
                            'X-CSRF-TOKEN': "{{ csrf_token() }}"
                        },
                        data: {
                            "_token": "{{ csrf_token() }}",
                            stock,
                            description
                        }
                    }).then((response) => {
                        Swal.fire({
                            icon: 'success',
                            title: "Success",
                            text: "Stock added",
                            showConfirmButton: true,
                            timer: 1500
                        }).then(() => {
                            location.reload()
                        })
                    }).catch((err) => {
                        Swal.fire({
                            icon: 'error',
                            title: 'Oops...',
                            text: err.response.data.message,
                        })
                    })
                }
            })
        }

        $(document).ready(function() {
            // DataTable
            $('#bookTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('books.json') }}",
                columns: [{
                        name: 'no',
                        data: 'id',
                        render: function(data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        },
                        orderable: false,
                    },
                    {
                        name: 'cover',
                        data: 'cover',
                        orderable: false
                    },
                    {
                        name: 'isbn',
                        data: 'isbn',
                        orderable: false
                    },
                    {
                        name: 'title',
                        data: 'title',
                        orderable: true,
                    },
                    {
                        name: 'category',
                        data: 'category',
                        orderable: false,
                    },
                    {
                        name: 'shelf',
                        data: 'shelf',
                        orderable: false,
                    },
                    {
                        name: 'stock',
                        data: 'stock',
                        orderable: true,
                    },
                    {
                        name: 'action',
                        data: 'action',
                        orderable: false
                    },
                ]
            });

        });
    </script>
@endpush